/* confdefs.h */
#define PACKAGE_NAME "hstr"
#define PACKAGE_TARNAME "hstr"
#define PACKAGE_VERSION "3.0.0"
#define PACKAGE_STRING "hstr 3.0.0"
#define PACKAGE_BUGREPORT "martin.dvorak@mindforger.com"
#define PACKAGE_URL ""
#define PACKAGE "hstr"
#define VERSION "3.0.0"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_LIBNCURSESW 1
#define HAVE_LIBM 1
#define HAVE_LIBREADLINE 1
#define HAVE__BOOL 1
#define HAVE_MALLOC 1
#define HAVE_MEMSET 1
#define HAVE_STRDUP 1
#define HAVE_STRSTR 1
